name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ankitc505/simple-time-service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # You can specify the version of Terraform you want here.

    - name: List files in the repository
      run: |
        echo "Current working directory:"
        pwd
        echo "List files in the repository:"
        ls -R

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG ./app
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Set image for Terraform
      run: echo "container_image=$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Debug Current Dir
      run: |
        pwd
        ls -la
        ls -la ./terraform

    - name: Terraform Init
      run: terraform init
      working-directory: terraform


    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve -var="container_image=$container_image"
